version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui/pages/rapid-response-react/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directories:
      - "/functions/Func_Jobs/"
      - "/functions/job_history/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
