version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui/pages/rapid-response-react/"
    open-pull-requests-limit: 15
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
  - package-ecosystem: "gomod"
    directories:
      - "/functions/Func_Jobs/"
      - "/functions/job_history/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
