name: Install software
description: Install and Update.
multi_instance: true
customer_visible: true
parameters:
  actions:
    configuration:
      put_and_run_file_b3305a8e:
        properties:
          file_name:
            required: true
          params:
            required: false
  conditions:
    FROM_platform_is_equal_to_windows_hostname_includes_to_parameterized_host_groups_includes_to_parameterize_831608b0_TO_activity_check_file_exist_rtr_2_e7dcae9e:
      fields:
        get_device_details_e84112c6.Device.GetDetails.Groups:
          required: false
          multiple: true
          operator: IN
        device_query_d360b503.Device.query.devices.#:
          required: false
          multiple: true
          operator: IN
  trigger:
    node_id: trigger
    fields:
      timer_event_definition:
        required: true
trigger:
  next:
    - update_job_history_df7b2f1b
  event: Schedule
actions:
  device_query_d360b503:
    next:
      - device_query_devices_07ddddab
    properties:
      device_status: all
  update_job_history_df7b2f1b:
    next:
      - device_query_d360b503
    properties:
      definition_name: "${Workflow.Definition.Name}"
      execution_id: "${Workflow.Execution.ID}"
      execution_timestamp: "${Workflow.Execution.Time}"
      status: In progress
loops:
  device_query_devices_07ddddab:
    for:
      input: device_query_d360b503.Device.query.devices
      continue_on_partial_execution: true
    trigger:
      next:
        - get_device_details_e84112c6
    actions:
      get_device_details_e84112c6:
        next:
          - FROM_platform_is_equal_to_windows_hostname_includes_to_parameterized_host_groups_includes_to_parameterize_831608b0_TO_activity_check_file_exist_rtr_2_e7dcae9e
        properties:
          device_id: "${device_query_d360b503.Device.query.devices.#}"
      put_and_run_file_b3305a8e:
        next:
          - write_data_into_logscale_9e2dc65c
        properties:
          device_id: "${device_query_d360b503.Device.query.devices.#}"
          queue_offline: true
      write_data_into_logscale_9e2dc65c:
        properties:
          foundry_app_id: ${{FOUNDRY_APP_ID}}
          _fields:
            - "${put_and_run_file_b3305a8e.RTR.PutAndRun.stderr}"
            - "${put_and_run_file_b3305a8e.RTR.PutAndRun.stdout}"
            - "${get_device_details_e84112c6.Device.GetDetails.Groups}"
            - "${get_device_details_e84112c6.Device.GetDetails.Hostname}"
            - "${device_query_d360b503.Device.query.devices.#}"
            - "${Trigger.Category.Schedule.}"
            - "${Workflow.Execution.ID}"
            - "${Workflow.Execution.Time}"
            - "${Workflow.Definition.Name}"
    conditions:
      FROM_platform_is_equal_to_windows_hostname_includes_to_parameterized_host_groups_includes_to_parameterize_831608b0_TO_activity_check_file_exist_rtr_2_e7dcae9e:
        next:
          - put_and_run_file_b3305a8e
        expression: get_device_details_e84112c6.Device.GetDetails.Platform:'Windows'
        display:
          - Platform is equal to Windows
          - Hostname includes to [parameterized]
            - Host groups includes to [parameterized]
